### ISSUE TITLE
connecting to uhfli 

### ISSUE THREAD

**Issue by josephhic** [zhinst/zhinst-qcodes#29]
There is a bug that prevents using the new API to establish a connection to the UHFLI. 

session.devices.connected() returns ['dev2454'], which is the ID of our instrument. When we then try 

session.devices['dev2454']

or equivalently 

session.connect_device('dev2454')

we get an error due to not having the AWG option installed on our instrument: 

>>> session.devices['dev2454']
The AWG option is not installed.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/triton5/.local/lib/python3.9/site-packages/zhinst/qcodes/session.py", line 47, in __getitem__
    self._devices[key] = ZIDevices.DEVICE_CLASS_BY_MODEL.get(
  File "/home/triton5/.local/lib/python3.9/site-packages/qcodes/instrument/base.py", line 508, in __call__
    new_inst = super().__call__(*args, **kwargs)
  File "/home/triton5/.local/lib/python3.9/site-packages/zhinst/qcodes/driver/devices/base.py", line 43, in __init__
    self._init_additional_nodes()
  File "/home/triton5/.local/lib/python3.9/site-packages/zhinst/qcodes/driver/devices/uhfli.py", line 203, in _init_additional_nodes
    if self._tk_object.awgs:
  File "/home/triton5/.local/lib/python3.9/site-packages/zhinst/toolkit/driver/devices/uhfli.py", line 33, in awgs
    for i in range(len(self["awgs"]))
  File "/home/triton5/.local/lib/python3.9/site-packages/zhinst/toolkit/nodetree/node.py", line 406, in __len__
    raise TypeError(f"Node {self.node_info.path} is not a list")
TypeError: Node /dev2454/awgs is not a list

There is no way that I can find to flag that the instrument doesn't have the AWG option or something like that.

**Comment by tobiasah** [comment]
Thanks for letting us know. 
It is indeed a bug in toolkit which we need to fix. I will keep you updated in this ticket. 

In the mean time you simply can use the ``raw=True`` option when connecting a device. This option prevents loading device specific adaptions. Since the AWG adaptions are currently the only device specific adaptions for the UHFLI, you do not loose any functionality.

```
session.connect_device('DEV2454', raw=True)
```
or 
```
from zhinst.qcodes import UHFLI
UHFLI('DEV2454',  'localhost', raw=True)
```
